repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.239'
    hooks:
      - id: ruff
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.1
    hooks:
      - id: autopep8
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: python api/hooks/pytest.py
        language: python
        types: [python]
  - repo: local
    hooks:
      - id: typos
        name: typos
        entry: python api/hooks/typos.py
        language: python
        types: [python]
